FROM php:8.4.19-apache

WORKDIR /var/www/html
RUN a2enmod rewrite
RUN a2enmod actions

RUN docker-php-ext-install pdo pdo_mysql mysqli


RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"  && \ 
mv composer.phar /usr/local/bin/composer

COPY ./Datos/composer.json .
COPY ./Datos/.env .

RUN apt-get update && apt-get install -y zip
RUN apt-get update && apt-get install -y git
RUN composer install 

RUN composer dump-autoload

RUN sed -i 's/DocumentRoot.*$/DocumentRoot \/var\/www\/html\/public/' /etc/apache2/sites-available/000-default.conf